/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelo;

/**
 *
 * @author usuario
 */
public enum TipoInsumo {
    //colocar aqui el tipo de insumos existentes
    AGUJAS,AGUA_GOULAR,AGUA_OXIGENADA,ALCOHOL,ALGODON,BAJA_LENGUA,BISTURI,
    CATETER_INTRAVENOSO,CETONA,ENVASES,EQUIPOS,ESPECULOS,ESPARADRAPOS,FORMOL,GASAS,GEL,GORROS_DESCARTABLES,
    GUANTES_DESCARTBLES,HILOS_DE_SUTURA,INSUMOS_DE_LABORATORIO,JERINGUILLAS,LIMPIEZA_QUIRURGICA,LLAVES_DE_TRES_VIAS,
    MARIPOSAS,MASCARILLAS,MERTIOLATE,SONDAS,SUEROS,TERMOMETROS,TRAJES_DESCARTABLES,TUBOS_DE_EXTRACCIÓN_AL_VACIO,
    TUBOS_ENDOTRAQUEALES,VENDAS,FARMACOS_AMPOLLAS,FARMACOS_ANESTESICOS,OTROS
}
